"""Initial Migration

Revision ID: 93a4a5291f00
Revises: c0dacff8a0e4
Create Date: 2019-07-08 10:31:32.495391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a4a5291f00'
down_revision = 'c0dacff8a0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_c_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_c', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_user_c_fkey', 'comments', 'users', ['user_c'], ['id'])
    # ### end Alembic commands ###
