"""Initial Migration

Revision ID: c0dacff8a0e4
Revises: 047f17d25192
Create Date: 2019-07-08 04:34:02.546650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dacff8a0e4'
down_revision = '047f17d25192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscribers_pkey'),
    sa.UniqueConstraint('email', name='subscribers_email_key')
    )
    # ### end Alembic commands ###
