"""Initial Migration

Revision ID: d5a110e893d7
Revises: 93a4a5291f00
Create Date: 2019-07-08 11:53:03.262576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a110e893d7'
down_revision = '93a4a5291f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_c', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['user_c'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_c')
    # ### end Alembic commands ###
